"""A Markdown report with figures, generated from a results directory.

Every figure comes in a light and a dark version inside a ``<picture>`` element, so GitHub
shows the one matching the reader's theme, and every figure has a table with the same
numbers next to it.
"""

from __future__ import annotations

import logging
from collections.abc import Sequence
from pathlib import Path

import numpy as np
import pandas as pd

from ivcrypto.compare import power_law
from ivcrypto.pipeline import Results
from ivcrypto.plots import draw_all

logger = logging.getLogger(__name__)

Column = tuple[str, str, str]
"""(column name, header, format spec) for :func:`markdown_table`."""


def markdown_table(frame: pd.DataFrame, columns: Sequence[Column]) -> str:
    header = "| " + " | ".join(h for _, h, _ in columns) + " |"
    rule = "|" + "|".join("---" for _ in columns) + "|"
    lines = [header, rule]
    for _, row in frame.iterrows():
        cells = []
        for name, _, spec in columns:
            value = row[name]
            if value is None or (isinstance(value, float) and np.isnan(value)):
                cells.append("")
            elif spec:
                cells.append(format(value, spec))
            else:
                cells.append(str(value))
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def _picture(name: str, alt: str, themes: Sequence[str]) -> str:
    light = f"figures/{name}_light.png"
    if "dark" not in themes:
        return f'<img alt="{alt}" src="{light}">'
    return (
        "<picture>\n"
        f'  <source media="(prefers-color-scheme: dark)" srcset="figures/{name}_dark.png">\n'
        f'  <img alt="{alt}" src="{light}">\n'
        "</picture>"
    )


def render(results: Results, themes: Sequence[str] = ("light", "dark")) -> str:
    m = results.manifest
    heston = m["heston"]
    ssvi = m["ssvi"]
    parts = [
        f"# {m['currency']} implied volatility report",
        "",
        f"Snapshot taken {m['snapshot_utc']} (quotes computed by Deribit at "
        f"{m['valuation_time']}), `{m['snapshot']}`. Generated by ivcrypto "
        f"{m['ivcrypto_version']}, commit `{m.get('git_commit') or 'unknown'}`. All IVs and "
        "errors are in percent and vol points; k = ln(K/F).",
        "",
        "## Cleaning",
        "",
        markdown_table(
            results["filters"],
            [("step", "Step", ""), ("removed", "Removed", "d"), ("remaining", "Remaining", "d")],
        ),
        "",
        markdown_table(
            results["forwards"],
            [
                ("expiry_code", "Expiry", ""),
                ("days", "Days", ".1f"),
                ("forward", "Forward", ",.1f"),
                ("forward_source", "Source", ""),
                ("parity_pairs_used", "Pairs", "d"),
                ("parity_scatter_bps", "Scatter (bps)", ".2f"),
                ("parity_se_bps", "Std error (bps)", ".2f"),
                ("parity_vs_underlying_bps", "Minus future (bps)", "+.2f"),
                ("regression_discount", "Coin discount", ".4f"),
            ],
        ),
        "",
        "## Implied volatility against Deribit",
        "",
        _picture("iv_validation", "Distributions of IV differences against Deribit", themes),
        "",
        markdown_table(
            results["validation_summary"].query("group in ['all', 'bid', 'ask']"),
            [
                ("comparison", "Comparison", ""),
                ("group", "Group", ""),
                ("n", "n", "d"),
                ("median", "Median", "+.4f"),
                ("p5", "5th pct", "+.4f"),
                ("p95", "95th pct", "+.4f"),
                ("max_abs", "Max abs", ".4f"),
                ("share_within_rounding", "Within rounding", ".1%"),
            ],
        ),
        "",
        "## Smiles",
        "",
        _picture("smiles", "Market bid ask bands and mids with SVI and Heston smiles", themes),
        "",
        markdown_table(
            results["svi"],
            [
                ("expiry_code", "Expiry", ""),
                ("days", "Days", ".1f"),
                ("n", "Quotes", "d"),
                ("atm_vol", "ATM vol", ".2%"),
                ("rho", "rho", "+.3f"),
                ("rmse_vol", "SVI RMSE", ".3f"),
                ("max_error_vol", "SVI max error", ".3f"),
                ("in_band_share", "SVI inside band", ".0%"),
                ("converged_starts", "Starts agreeing", "d"),
                ("active_bounds", "Binding bounds", ""),
            ],
        ),
        "",
        f"SSVI (one surface, arbitrage free by construction): rho = {ssvi['rho']:+.3f}, "
        f"eta = {ssvi['eta']:.3f}, gamma = {ssvi['gamma']:.3f}.",
        "",
        markdown_table(
            results["ssvi"],
            [
                ("expiry_code", "Expiry", ""),
                ("days", "Days", ".1f"),
                ("theta", "theta", ".5f"),
                ("rmse_vol", "SSVI RMSE", ".3f"),
                ("in_band_share", "SSVI inside band", ".0%"),
            ],
        ),
        "",
        "## Static arbitrage",
        "",
        "Per expiry SVI fits and raw quotes:",
        "",
        markdown_table(
            results["arbitrage_tests"],
            [
                ("check", "Check", ""),
                ("prices", "Prices", ""),
                ("tested", "Tests", "d"),
                ("violations", "Violations", "d"),
                ("violations_in_quoted_range", "Inside quoted range", "d"),
            ],
        ),
        "",
        "SSVI, at the expiries and at maturities in between:",
        "",
        markdown_table(
            results["ssvi_arbitrage_tests"],
            [
                ("check", "Check", ""),
                ("tested", "Tests", "d"),
                ("violations", "Violations", "d"),
            ],
        ),
        "",
        "## Heston",
        "",
        f"One parameter set: v0 = {heston['v0']:.4f}, kappa = {heston['kappa']:.3f}, "
        f"theta = {heston['theta']:.4f}, xi = {heston['xi']:.3f}, rho = {heston['rho']:+.3f}; "
        f"Feller ratio 2 kappa theta / xi^2 = {heston['feller_ratio']:.3f} "
        f"({'satisfied' if heston['feller_ratio'] >= 1 else 'violated'}).",
        "",
        _picture("residual_heatmaps", "Mean model minus mid IV by expiry and moneyness", themes),
        "",
        _comparison_tables(results),
        "",
        _picture("atm_term_structure", "ATM vol and ATM curvature against maturity", themes),
        "",
        _atm_table(results),
        "",
        "## Surface",
        "",
        _picture("surface", "SVI implied volatility surface", themes),
        "",
    ]
    per_expiry = results.get("heston_per_expiry")
    if per_expiry is not None:
        parts[parts.index("## Surface") : parts.index("## Surface")] = [
            "Heston fitted to each expiry separately:",
            "",
            markdown_table(
                per_expiry,
                [
                    ("expiry_code", "Expiry", ""),
                    ("days", "Days", ".1f"),
                    ("v0", "v0", ".3f"),
                    ("kappa", "kappa", ".1f"),
                    ("theta", "theta", ".3f"),
                    ("xi", "xi", ".2f"),
                    ("rho", "rho", "+.2f"),
                    ("feller_ratio", "Feller ratio", ".2f"),
                    ("rmse_vol", "RMSE", ".3f"),
                    ("in_band_share", "Inside band", ".0%"),
                ],
            ),
            "",
        ]
    return "\n".join(parts)


def _comparison_tables(results: Results) -> str:
    columns: list[Column] = [("group", "Quotes", ""), ("n", "n", "d")]
    frame = pd.concat(
        [
            results["comparison_overall"],
            results["comparison_by_maturity"],
            results["comparison_by_moneyness"],
        ],
        ignore_index=True,
    )
    for model in ("SVI", "SSVI", "Heston", "Heston per expiry"):
        if f"{model} rmse" in frame:
            columns.append((f"{model} rmse", f"{model} RMSE", ".2f"))
    for model in ("SVI", "Heston"):
        columns.append((f"{model} inside_band", f"{model} inside band", ".0%"))
    return markdown_table(frame, columns)


def _atm_table(results: Results) -> str:
    ts = results["atm_term_structure"]
    _, alpha_market = power_law(ts["T"], ts["market_atm_curvature"])
    _, alpha_heston = power_law(ts["T"], ts["heston_atm_curvature"])
    table = markdown_table(
        ts,
        [
            ("expiry_code", "Expiry", ""),
            ("days", "Days", ".1f"),
            ("market_atm_vol", "Market ATM vol", ".2%"),
            ("heston_atm_vol", "Heston ATM vol", ".2%"),
            ("market_atm_skew", "Market skew", "+.3f"),
            ("heston_atm_skew", "Heston skew", "+.3f"),
            ("market_atm_curvature", "Market curvature", ".3f"),
            ("heston_atm_curvature", "Heston curvature", ".3f"),
        ],
    )
    return (
        f"{table}\n\nPower law fits of ATM curvature c T^-alpha: market alpha = "
        f"{alpha_market:.2f}, Heston alpha = {alpha_heston:.2f}."
    )


def write_report(
    results: Results, out_dir: Path | str, themes: Sequence[str] = ("light", "dark")
) -> Path:
    out_dir = Path(out_dir)
    draw_all(results, out_dir / "figures", tuple(themes))
    path = out_dir / "report.md"
    path.write_text(render(results, themes) + "\n", encoding="utf-8")
    logger.info("report written to %s", path)
    return path
